services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTG-ES_USER=postgres
      - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
      - POSTGRES_DB=meridian-grid-db
    ports:
      - "5432:5432"
    volumes:
      - meridian_grid_db_data:/var/lib/postgresql/data
volumes: 
  meridian_grid_db_data: